name: project_travelplanner
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0 # Or the version you are using
  google_fonts: ^6.1.0 # Or the version you are using
  http: ^1.1.0 # Or the version you are using
  # ... other dependencies

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  http: ^1.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
